votacao/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('voting.urls'), name='voting'),
]

voting/urls.py
from __future__ import unicode_literals

from django.urls import include, path
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views

from . import views as voting

app_name = 'voting'

urlpatterns = [

    path('', voting.Index.as_view(), name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('usuarios/novo/', voting.UserCreateView.as_view(), name='user-create'),
    path('criarproposta/', voting.AddProposalView.as_view(), name='proposal-create'),
    path('vote/<pk>', voting.Vote.as_view(), name='vote'),
    path('votosim/', voting.Approve.as_view(), name='votosim'),
    path('comentar/', voting.CommentView.as_view(), name='comentar'),
    path('comentarios/<pk>/', voting.Vote2.as_view(), name='comentarios'),
]

voting/models.py
from __future__ import unicode_literals

import uuid


from django.db import models
from django.utils import timezone
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.contrib.auth.models import AbstractUser, Group, Permission

class CreateUpdateModel(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created_at = models.DateTimeField('criado em', auto_now_add=True)
    updated_at = models.DateTimeField('atualizado em', auto_now=True)

    class Meta:
        abstract = True

class UUIDUser(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    groups = models.ManyToManyField(Group, blank=True, related_name="uuiduser_set", related_query_name="user")
    user_permissions = models.ManyToManyField(Permission, blank=True, related_name="uuiduser_set", related_query_name="user")

    def __str__(self):
     return "%s" %(self.first_name)
  
    class Meta:
        verbose_name = 'usuario'
        verbose_name_plural = 'usuarios'

class Proposal(CreateUpdateModel):
    user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='UUIDUser')
    name = models.CharField(max_length=150, verbose_name='nome')
    description = models.TextField(verbose_name='descrição')

    def __str__(self):
     return "%s" %(self.name)

    class Meta:
        verbose_name = 'proposta'
        verbose_name_plural = 'propostas'

class Vote(models.Model):
    kindchoice = (
        (1, 'sim'),
        (2, 'não')
    )
    user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='UUIDUser2')
    kind = models.IntegerField(choices=kindchoice, verbose_name="tipo")
    proposal = models.ForeignKey(Proposal, on_delete=models.CASCADE, related_name='proposta')


    def __str__(self):
        return "%s" %(self.kind)

    class Meta:
        verbose_name = 'voto'
        verbose_name_plural = 'votos'

class Comment(models.Model):
    user = models.ForeignKey(UUIDUser, on_delete=models.CASCADE, related_name='UUIDUser3')
    text = models.TextField(verbose_name='comentário')
    proposal = models.ForeignKey(Proposal, on_delete=models.CASCADE, related_name='proposta2')

    def __str__(self):
        return "%s" %(self.text)

    class Meta:
        verbose_name = 'comentário'
        verbose_name_plural = 'comentários'

voting/forms.py
from django import forms

from . import models

class RegistrationUserForm(forms.ModelForm):
  
  class Meta:
    model = models.UUIDUser
    fields = ('first_name', 'last_name', 'username', 'email', 'password')
    labels = {
    	'first_name': 'Primeiro Nome',
    	'last_name': 'Sobrenome',
    	'username': 'Nome de Usuário',
    	'email': 'E-mail',
    	'password': 'Senha',
    }
    widgets = {
      'password': forms.PasswordInput()
    }

class AddProposal(forms.ModelForm):

	class Meta:
		model = models.Proposal
		fields = ('name', 'description')
		labels = {
    		'name': 'Nome da Proposta',
    		'description': 'Descrição',
    	}

class ApproveForm(forms.ModelForm):
		class Meta:
			model = models.Vote
			aux = models.Vote.objects.all()
			fields = ('kind', 'proposal')
			labels = {
				'kind': 'Tipo:',
				'proposal': 'Proposta',
			}

class CommentForm(forms.ModelForm):
		class Meta:
			model = models.Comment
			fields = ('text', 'proposal')
			labels = {
					'text': 'Comente:',
					'proposal': 'Proposta',
				}	

voting/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.urls import reverse_lazy
from django.views import View
from django.http import HttpResponse

from . import models
from .forms import *

class Index(ListView):
    template_name = 'index.html'
    model = models.Proposal

class UserCreateView(CreateView):
    model = models.UUIDUser
    template_name = 'cadastro.html'
    success_url = reverse_lazy('voting:login')
    form_class = RegistrationUserForm

    def form_valid(self, form):
    	obj = form.save(commit=False)
    	obj.set_password(obj.password)
    	obj.save()
    	return super(UserCreateView, self).form_valid(form)

class AddProposalView(CreateView):
	model = models.Proposal
	template_name = 'add-proposal.html'
	success_url = reverse_lazy('voting:index')
	form_class = AddProposal

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		obj.save()
		return super(AddProposalView, self).form_valid(form)

class Vote(DetailView):
	model = models.Proposal
	template_name = 'proposta.html'

	def get_context_data(self, **kwargs):
		#kwargs['proposals'] = models.Proposal.objects.all()
		kwargs['comments'] = models.Comment.objects.filter(proposal = self.object.pk)
		return super(Vote, self).get_context_data(**kwargs)


class Vote2(DetailView):
	model = models.Proposal
	template_name = 'comment_list.html'
	
	def get_context_data(self, **kwargs):
		kwargs['comments'] = models.Comment.objects.filter(proposal = self.object.pk)
		return super(Vote2, self).get_context_data(**kwargs)

class Approve(CreateView):
	model = models.Vote
	template_name = 'votosim.html'
	success_url = reverse_lazy('voting:index')
	form_class = ApproveForm

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		obj.save()
		return super(Approve, self).form_valid(form)
	# def get_queryset(self):
	# 	if 'proposal' in self.request.GET:
	# 		return models.Vote.objects.filter(proposal=self.request.GET['proposal'])
	# 	return models.Vote.objects.all()
class CommentView(CreateView):
	model = models.Comment
	template_name = 'comment.html'
	success_url = reverse_lazy('voting:index')
	form_class = CommentForm

	def form_valid(self, form):
		obj = form.save(commit=False)
		obj.user = self.request.user
		obj.save()
		return super(CommentView, self).form_valid(form)
# class VoteUp(UpdateView):
# 	model = models.Proposal
# 	template_name = 
# 	success_url = reverse_lazy()
# 	fields = ['comment']

templates/add-proposal.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<form action='', method='POST'>
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Cadastrar proposta">
</form>
</body>
</html>

templates/cadastro.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<div style = 'text-align: center;'>
<h1>Cadastro</h1>
<form action='', method='POST'>
    {%csrf_token%}
    {% for field in form.visible_fields %}
    <span class="txt1 p-b-11">
        {{ field.label }}
    </span>
  <div class="wrap-input100 validate-input m-b-36">
      {{ field }}
      <span class="focus-input100"></span>
      {% for error in field.errors %}
        <span class="help-block">{{ error }}</span>
      {% endfor %}
    </div>
    
{% endfor %}
<input type="submit" value="Cadastrar">
</form>
</div>
</body>
</html>

templates/comment.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<a href="{% url 'voting:index'%}">Voltar</a>
<form action='', method='POST'>
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Comentar">
</form>
</body>
</html>

templates/comment_list.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<a href="{% url 'voting:index'%}">Voltar</a>
<h1> Comentários </h1>
    {%for a in comments%}
    <ul>
        <li>{{a.user}} - {{a.text}} </a></li>   
    </ul>
    {%endfor%}
</body>
</html>

templates/index.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
{%if request.user.is_authenticated%}
<div style = 'text-align: center;'>    
<a href='/logout/'><button>Logout</button></a>
<a href='/criarproposta/'><button>Criar proposta</button></a>
</div>
{%else%}
<div style = 'text-align: center;'>
    <a href='/login/'><button>Login</button></a>
    <a href='/usuarios/novo/'><button>Cadastre-se</button></a>
</div>
{%endif%}
<div>
    <h1>Lista de propostas:</h1>
{%for x in object_list%}
<ul>
    <li><a href="{% url 'voting:vote' x.pk %}">{{x.name}}</a></li>
    {{x.description}}
    <!-- {%if request.user.is_authenticated%}
    <button type="submit">Sim</button>
    <button type="submit">Não</button>
    <br>
    <label for "message">Comentário</label>
    <textarea type="message" name="comment"></textarea>
    </br>
    {%endif%} -->
</ul>
{%endfor%}
</div>
</body>
</html>

templates/login.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<div style = 'text-align: center;'>
    <h1>Login</h1>
</div>
<div style = 'text-align: center;'>
<form action='', method='POST'>
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Entrar">
</form>
</div>
</body>
</html>

templates/proposta.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<a href="{% url 'voting:index'%}">Voltar</a>
<div>
{%if request.user.is_authenticated%}
<h2>{{object.name}}</h2>
<p>{{object.description}}</p>
<a href='/votosim/'><button type="submit">Voto</button></a>
</div>
<div>
<a href='/comentar/'><button type="submit">Comentar</button></a>
<!-- <a href="{% url 'voting:comentarios' object.pk %}"><button type="submit">Comentários</button></a> -->
{%else%}
<h2>{{object.name}}</h2>
<p>{{object.description}}</p>
{%endif%}
<h1> Comentários </h1>
    {%for a in comments%}
    <ul>
        <li>{{a.user}} - {{a.text}} </a></li>   
    </ul>
    {%endfor%}
</div>
</body>
</html>

templates/votosim.html
<html>
<head>
<title>Sistema de Votação</title>
</head>
<body>
<a href="{% url 'voting:index'%}">Voltar</a>
<form action='', method='POST'>
        {%csrf_token%}
        {{form.as_p}}
        <input type="submit" value="Cadastrar voto">
</form>
</body>
</html>